jenkins-slave:
  container_name: jenkins-slave-android
  restart: always
  #image: accenture/adop-jenkins-slave:0.1.4
  build: ./jenkins-slave-android
  net: local_network
  privileged: true
  environment:
    SLAVE_LABELS: "android"
    SWARM_PASSWORD: ${SWARM_PASSWORD}
    SLAVE_EXECUTORS: ${SLAVE_EXECUTORS}
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD}


android-emulator:
  #net: ${CUSTOM_NETWORK_NAME}
  container_name: android-emulator
  restart: always
  build: ./android-emulator
  ports:
    - "5555:5555"
    - "5900:5900"


