jenkins-slave:
  container_name: jenkins-slave-android
  restart: always
  #image: accenture/adop-jenkins-slave:0.1.4
  build: ./jenkins-slave-android
  net: ${CUSTOM_NETWORK_NAME}
  privileged: true
  environment:
    SLAVE_LABELS: "android"
    SWARM_PASSWORD: ${PASSWORD_JENKINS}
    SLAVE_EXECUTORS: 1
    INITIAL_ADMIN_USER: ${INITIAL_ADMIN_USER}
    INITIAL_ADMIN_PASSWORD: ${INITIAL_ADMIN_PASSWORD_PLAIN}
